package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttendanceReason generated by hbm2java
 */
@Entity
@Table(name="attendance_reason"
)
@JsonIdentityInfo(
		generator = ObjectIdGenerators.StringIdGenerator.class,
		property="attendanceReasonId")
public class AttendanceReason  implements java.io.Serializable {


	 private Integer id;
	 private String code;
	 private String description;
	 private Set<StudentAttendance> studentAttendances = new HashSet<StudentAttendance>(0);

	public AttendanceReason() {
	}

	
	public AttendanceReason(String code, String description) {
		this.code = code;
		this.description = description;
	}
	public AttendanceReason(String code, String description, Set<StudentAttendance> studentAttendances) {
	   this.code = code;
	   this.description = description;
	   this.studentAttendances = studentAttendances;
	}
   
	 @Id @GeneratedValue(strategy=IDENTITY)
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name="code", nullable=false, length=20)
	public String getCode() {
		return this.code;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	@Column(name="description", nullable=false, length=45)
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="attendanceReason")
	public Set<StudentAttendance> getStudentAttendances() {
		return this.studentAttendances;
	}
	
	public void setStudentAttendances(Set<StudentAttendance> studentAttendances) {
		this.studentAttendances = studentAttendances;
	}




}


