package com.dev.ams.model;
// Generated Mar 3, 2019, 11:29:41 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities"
)
public class Authorities implements java.io.Serializable {


    private String id;

    @JsonBackReference(value="authority")
    private Users users;
    private String authority;

    public Authorities() {
    }

    public Authorities(String id, Users users, String authority) {
        this.id = id;
        this.users = users;
        this.authority = authority;
    }

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 45)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "authority", nullable = false, length = 50)
    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }


}


