package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseCalendar generated by hbm2java
 */
@Entity
@Table(name = "base_calendar")
public class BaseCalendar implements java.io.Serializable {


    private Integer baseCalendarId;
    private String month;
    private String day;
    private String year;
    private String holidayName;
    private String holidayDescription;

    public BaseCalendar() {
    }

    public BaseCalendar(Integer baseCalendarId, String month, String day, String year, String holidayName, String holidayDescription) {
        this.baseCalendarId = baseCalendarId;
        this.month = month;
        this.day = day;
        this.year = year;
        this.holidayName = holidayName;
        this.holidayDescription = holidayDescription;
    }

    @Id
    @Column(name = "base_calendar_id", unique = true, nullable = false)
    public Integer getBaseCalendarId() {
        return this.baseCalendarId;
    }

    public void setBaseCalendarId(Integer baseCalendarId) {
        this.baseCalendarId = baseCalendarId;
    }

    @Column(name = "month", nullable = false, length = 45)
    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @Column(name = "day", nullable = false, length = 45)
    public String getDay() {
        return this.day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    @Column(name = "year", nullable = false, length = 45)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @Column(name = "holiday_name", nullable = false, length = 45)
    public String getHolidayName() {
        return this.holidayName;
    }

    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName;
    }

    @Column(name = "holiday_description", nullable = false, length = 45)
    public String getHolidayDescription() {
        return this.holidayDescription;
    }

    public void setHolidayDescription(String holidayDescription) {
        this.holidayDescription = holidayDescription;
    }


}


