package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchTimings generated by hbm2java
 */
@Entity
@Table(name="batch_timings"
)
@JsonIdentityInfo(
		generator = ObjectIdGenerators.StringIdGenerator.class,
		property="batchTimingsId")
public class BatchTimings  implements java.io.Serializable {


	 private Integer id;
	 private Batch batch;
	 private Date startTime;
	 private Date endTime;
	 private String day;
	 private char isBreak;

	public BatchTimings() {
	}

	public BatchTimings(Batch batch, Date startTime, Date endTime, String day, char isBreak) {
	   this.batch = batch;
	   this.startTime = startTime;
	   this.endTime = endTime;
	   this.day = day;
	   this.isBreak = isBreak;
	}
   
	 @Id @GeneratedValue(strategy=IDENTITY)
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="batch_id", nullable=false)
	public Batch getBatch() {
		return this.batch;
	}
	
	public void setBatch(Batch batch) {
		this.batch = batch;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="start_time", nullable=false, length=19)
	public Date getStartTime() {
		return this.startTime;
	}
	
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="end_time", nullable=false, length=19)
	public Date getEndTime() {
		return this.endTime;
	}
	
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	
	@Column(name="day", nullable=false, length=10)
	public String getDay() {
		return this.day;
	}
	
	public void setDay(String day) {
		this.day = day;
	}
	
	@Column(name="is_break", nullable=false, length=1)
	public char getIsBreak() {
		return this.isBreak;
	}
	
	public void setIsBreak(char isBreak) {
		this.isBreak = isBreak;
	}




}


