package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name="batch"
)
public class Batch	implements java.io.Serializable {


	 private Integer id;
	 private Date year;
	 private Set<LectureSchedule> lectureSchedules = new HashSet<LectureSchedule>(0);

	public Batch() {
	}

	
	public Batch(Date year) {
		this.year = year;
	}
	public Batch(Date year, Set<LectureSchedule> lectureSchedules) {
	   this.year = year;
	   this.lectureSchedules = lectureSchedules;
	}
   
	 @Id @GeneratedValue(strategy=IDENTITY)
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="year", nullable=false, length=10)
	public Date getYear() {
		return this.year;
	}
	
	public void setYear(Date year) {
		this.year = year;
	}
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="batch")
	public Set<LectureSchedule> getLectureSchedules() {
		return this.lectureSchedules;
	}
	
	public void setLectureSchedules(Set<LectureSchedule> lectureSchedules) {
		this.lectureSchedules = lectureSchedules;
	}




}


