package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Board generated by hbm2java
 */
@Entity
@Table(name = "board"
)
public class Board implements java.io.Serializable {


    private Integer boardId;
    private String boardName;
    private Integer batchId;

    @JsonManagedReference(value = "standard-board")
    private Set<Standard> standards = new HashSet<Standard>(0);

    public Board() {
    }


    public Board(String boardName) {
        this.boardName = boardName;
    }

    public Board(String boardName, Integer batchId, Set<Standard> standards) {
        this.boardName = boardName;
        this.batchId = batchId;
        this.standards = standards;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "board_id", unique = true, nullable = false)
    public Integer getBoardId() {
        return this.boardId;
    }

    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    @Column(name = "board_name", nullable = false, length = 45)
    public String getBoardName() {
        return this.boardName;
    }

    public void setBoardName(String boardName) {
        this.boardName = boardName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "board")
    public Set<Standard> getStandards() {
        return this.standards;
    }

    public void setStandards(Set<Standard> standards) {
        this.standards = standards;
    }

    @Column(name = "batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }

    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

}


