package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChapterDetails generated by hbm2java
 */
@Entity
@Table(name="chapter_details"
)
public class ChapterDetails  implements java.io.Serializable {


	 private Integer id;
	 private Users users;
	 private Integer chapterNumber;
	 private Integer hours;
	 private Date date;

	public ChapterDetails() {
	}

	public ChapterDetails(Integer id, Users users, Integer chapterNumber, Integer hours, Date date) {
	   this.id = id;
	   this.users = users;
	   this.chapterNumber = chapterNumber;
	   this.hours = hours;
	   this.date = date;
	}
   
	 @Id 
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="taken_by", nullable=false)
	public Users getUsers() {
		return this.users;
	}
	
	public void setUsers(Users users) {
		this.users = users;
	}
	
	@Column(name="chapter_number", nullable=false)
	public Integer getChapterNumber() {
		return this.chapterNumber;
	}
	
	public void setChapterNumber(Integer chapterNumber) {
		this.chapterNumber = chapterNumber;
	}
	
	@Column(name="hours", nullable=false)
	public Integer getHours() {
		return this.hours;
	}
	
	public void setHours(Integer hours) {
		this.hours = hours;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="date", nullable=false, length=10)
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}




}


