package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChapterDetails generated by hbm2java
 */
@Entity
@Table(name="chapter_details"
)
public class ChapterDetails  implements java.io.Serializable {


	 private Integer id;
	 private Chapter chapter;
	 private EmployeeDetails employeeDetails;
	 private Batch batch;
	 private Date startDate;
	 private Date endDate;
	 private Integer hoursTaken;

	public ChapterDetails() {
	}

	
	public ChapterDetails(Chapter chapter, EmployeeDetails employeeDetails, Batch batch) {
		this.chapter = chapter;
		this.employeeDetails = employeeDetails;
		this.batch = batch;
	}
	public ChapterDetails(Chapter chapter, EmployeeDetails employeeDetails, Batch batch, Date startDate, Date endDate, Integer hoursTaken) {
	   this.chapter = chapter;
	   this.employeeDetails = employeeDetails;
	   this.batch = batch;
	   this.startDate = startDate;
	   this.endDate = endDate;
	   this.hoursTaken = hoursTaken;
	}
   
	 @Id @GeneratedValue(strategy=IDENTITY)
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="chapter_id", nullable=false)
	public Chapter getChapter() {
		return this.chapter;
	}
	
	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="employee_details_id", nullable=false)
	public EmployeeDetails getEmployeeDetails() {
		return this.employeeDetails;
	}
	
	public void setEmployeeDetails(EmployeeDetails employeeDetails) {
		this.employeeDetails = employeeDetails;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="batch_id", nullable=false)
	public Batch getBatch() {
		return this.batch;
	}
	
	public void setBatch(Batch batch) {
		this.batch = batch;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="start_date", length=10)
	public Date getStartDate() {
		return this.startDate;
	}
	
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="end_date", length=10)
	public Date getEndDate() {
		return this.endDate;
	}
	
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	@Column(name="hours_taken")
	public Integer getHoursTaken() {
		return this.hoursTaken;
	}
	
	public void setHoursTaken(Integer hoursTaken) {
		this.hoursTaken = hoursTaken;
	}




}


