package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name = "chapter")
public class Chapter implements java.io.Serializable {


    private Integer chapterId;
    private Users users;
    private Subject subject;
    private String chapterNumber;
    private String chapterName;
    private Date startDate;
    private Date finishDate;
    private Integer timeTaken;
    private String status;

    public Chapter() {
    }


    public Chapter(Integer chapterId, Subject subject, String chapterNumber, String chapterName, String status) {
        this.chapterId = chapterId;
        this.subject = subject;
        this.chapterNumber = chapterNumber;
        this.chapterName = chapterName;
        this.status = status;
    }

    public Chapter(Integer chapterId, Users users, Subject subject, String chapterNumber, String chapterName, Date startDate, Date finishDate, Integer timeTaken, String status) {
        this.chapterId = chapterId;
        this.users = users;
        this.subject = subject;
        this.chapterNumber = chapterNumber;
        this.chapterName = chapterName;
        this.startDate = startDate;
        this.finishDate = finishDate;
        this.timeTaken = timeTaken;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name = "chapter_id", unique = true, nullable = false)
    public Integer getChapterId() {
        return this.chapterId;
    }

    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taken_by")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @Column(name = "chapter_number", nullable = false, length = 45)
    public String getChapterNumber() {
        return this.chapterNumber;
    }

    public void setChapterNumber(String chapterNumber) {
        this.chapterNumber = chapterNumber;
    }

    @Column(name = "chapter_name", nullable = false, length = 45)
    public String getChapterName() {
        return this.chapterName;
    }

    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "start_date", length = 10)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "finish_date", length = 10)
    public Date getFinishDate() {
        return this.finishDate;
    }

    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    @Column(name = "time_taken")
    public Integer getTimeTaken() {
        return this.timeTaken;
    }

    public void setTimeTaken(Integer timeTaken) {
        this.timeTaken = timeTaken;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


}


