package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeDetails generated by hbm2java
 */
@Entity
@Table(name = "employee_details"
)
@JsonIdentityInfo(
        generator = ObjectIdGenerators.StringIdGenerator.class,
        property = "employeeDetailsId")
public class EmployeeDetails implements java.io.Serializable {


    private Integer id;

    @JsonIgnore
    private Users users;
    private Integer empNumber;
    private Date joiningDate;
    private String jobTitle;
    private String qualication;
    private Integer expYear;
    private String martialStatus;
    private Set<ChapterDetails> chapterDetailses = new HashSet<ChapterDetails>(0);

    public EmployeeDetails() {
    }


    public EmployeeDetails(Users users, Integer empNumber) {
        this.users = users;
        this.empNumber = empNumber;
    }

    public EmployeeDetails(Users users, Integer empNumber, Date joiningDate, String jobTitle, String qualication, Integer expYear, String martialStatus, Set<ChapterDetails> chapterDetailses) {
        this.users = users;
        this.empNumber = empNumber;
        this.joiningDate = joiningDate;
        this.jobTitle = jobTitle;
        this.qualication = qualication;
        this.expYear = expYear;
        this.martialStatus = martialStatus;
        this.chapterDetailses = chapterDetailses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "emp_number", nullable = false)
    public Integer getEmpNumber() {
        return this.empNumber;
    }

    public void setEmpNumber(Integer empNumber) {
        this.empNumber = empNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "joining_date", length = 10)
    public Date getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    @Column(name = "job_title", length = 45)
    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    @Column(name = "qualication", length = 45)
    public String getQualication() {
        return this.qualication;
    }

    public void setQualication(String qualication) {
        this.qualication = qualication;
    }

    @Column(name = "exp_year")
    public Integer getExpYear() {
        return this.expYear;
    }

    public void setExpYear(Integer expYear) {
        this.expYear = expYear;
    }

    @Column(name = "martial_status", length = 45)
    public String getMartialStatus() {
        return this.martialStatus;
    }

    public void setMartialStatus(String martialStatus) {
        this.martialStatus = martialStatus;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "employeeDetails")
    public Set<ChapterDetails> getChapterDetailses() {
        return this.chapterDetailses;
    }

    public void setChapterDetailses(Set<ChapterDetails> chapterDetailses) {
        this.chapterDetailses = chapterDetailses;
    }


}


