package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name="exam_result"
)
public class ExamResult  implements java.io.Serializable {


	 private ExamResultId id;
	 private Exam exam;
	 private StudentDetails studentDetails;
	 private Integer marksObtained;
	 private String grade;

	public ExamResult() {
	}

	public ExamResult(ExamResultId id, Exam exam, StudentDetails studentDetails, Integer marksObtained, String grade) {
	   this.id = id;
	   this.exam = exam;
	   this.studentDetails = studentDetails;
	   this.marksObtained = marksObtained;
	   this.grade = grade;
	}
   
	 @EmbeddedId
	
	@AttributeOverrides( {
		@AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
		@AttributeOverride(name="studentDetailsId", column=@Column(name="student_details_id", nullable=false) ) } )
	public ExamResultId getId() {
		return this.id;
	}
	
	public void setId(ExamResultId id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="exam_id", nullable=false)
	public Exam getExam() {
		return this.exam;
	}
	
	public void setExam(Exam exam) {
		this.exam = exam;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="student_details_id", nullable=false, insertable=false, updatable=false)
	public StudentDetails getStudentDetails() {
		return this.studentDetails;
	}
	
	public void setStudentDetails(StudentDetails studentDetails) {
		this.studentDetails = studentDetails;
	}
	
	@Column(name="marks_obtained", nullable=false)
	public Integer getMarksObtained() {
		return this.marksObtained;
	}
	
	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}
	
	@Column(name="grade", nullable=false, length=45)
	public String getGrade() {
		return this.grade;
	}
	
	public void setGrade(String grade) {
		this.grade = grade;
	}




}


