package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name="exam"
)
public class Exam  implements java.io.Serializable {


	 private Integer id;
	 private Subject subject;
	 private String questionPaper;
	 private Date date;
	 private String status;
	 private String postponedDates;
	 private Integer totalMarks;
	 private Set<ExamResult> examResults = new HashSet<ExamResult>(0);

	public Exam() {
	}

	
	public Exam(Integer id, Subject subject, String questionPaper, Date date, String status, Integer totalMarks) {
		this.id = id;
		this.subject = subject;
		this.questionPaper = questionPaper;
		this.date = date;
		this.status = status;
		this.totalMarks = totalMarks;
	}
	public Exam(Integer id, Subject subject, String questionPaper, Date date, String status, String postponedDates, Integer totalMarks, Set<ExamResult> examResults) {
	   this.id = id;
	   this.subject = subject;
	   this.questionPaper = questionPaper;
	   this.date = date;
	   this.status = status;
	   this.postponedDates = postponedDates;
	   this.totalMarks = totalMarks;
	   this.examResults = examResults;
	}
   
	 @Id 
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="subject_id", nullable=false)
	public Subject getSubject() {
		return this.subject;
	}
	
	public void setSubject(Subject subject) {
		this.subject = subject;
	}
	
	@Column(name="question_paper", nullable=false)
	public String getQuestionPaper() {
		return this.questionPaper;
	}
	
	public void setQuestionPaper(String questionPaper) {
		this.questionPaper = questionPaper;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="date", nullable=false, length=10)
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name="status", nullable=false, length=55)
	public String getStatus() {
		return this.status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name="postponed_dates", length=500)
	public String getPostponedDates() {
		return this.postponedDates;
	}
	
	public void setPostponedDates(String postponedDates) {
		this.postponedDates = postponedDates;
	}
	
	@Column(name="total_marks", nullable=false)
	public Integer getTotalMarks() {
		return this.totalMarks;
	}
	
	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="exam")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}
	
	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}




}


