package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * FeesCollection generated by hbm2java
 */
@Entity
@Table(name = "fees_collection"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class FeesCollection implements java.io.Serializable {


    private Integer id;

    @JsonIgnore
    private StudentDetails studentDetails;
    private String feesTitle;
    private Integer amount;
    private Date paymentDate;
    private String payeeName;
    private String receiptNumber;
    private String paymentMode;
    private Date nextPaymentDate;

    public FeesCollection() {
    }


    public FeesCollection(StudentDetails studentDetails, Integer amount, Date paymentDate, String payeeName) {
        this.studentDetails = studentDetails;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.payeeName = payeeName;
    }

    public FeesCollection(StudentDetails studentDetails, String feesTitle, Integer amount, Date paymentDate, String payeeName, String receiptNumber, String paymentMode, Date nextPaymentDate) {
        this.studentDetails = studentDetails;
        this.feesTitle = feesTitle;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.payeeName = payeeName;
        this.receiptNumber = receiptNumber;
        this.paymentMode = paymentMode;
        this.nextPaymentDate = nextPaymentDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    public StudentDetails getStudentDetails() {
        return this.studentDetails;
    }

    public void setStudentDetails(StudentDetails studentDetails) {
        this.studentDetails = studentDetails;
    }

    @Column(name = "fees_title", length = 45)
    public String getFeesTitle() {
        return this.feesTitle;
    }

    public void setFeesTitle(String feesTitle) {
        this.feesTitle = feesTitle;
    }

    @Column(name = "amount", nullable = false)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "payment_date", nullable = false, length = 10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    @Column(name = "payee_name", nullable = false, length = 45)
    public String getPayeeName() {
        return this.payeeName;
    }

    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName;
    }

    @Column(name = "receipt_number", length = 45)
    public String getReceiptNumber() {
        return this.receiptNumber;
    }

    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    @Column(name = "payment_mode", length = 45)
    public String getPaymentMode() {
        return this.paymentMode;
    }

    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "next_payment_date", length = 10)
    public Date getNextPaymentDate() {
        return this.nextPaymentDate;
    }

    public void setNextPaymentDate(Date nextPaymentDate) {
        this.nextPaymentDate = nextPaymentDate;
    }

}


