package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name = "institute"
)

public class Institute implements java.io.Serializable {


    private Integer id;
    private String code;
    private String name;
    private byte[] logo;
    private Date created;
    private String theme;
    private Set<Users> userses = new HashSet<Users>(0);
    private Set<Board> boards = new HashSet<Board>(0);

    public Institute() {
    }


    public Institute(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public Institute(String code, String name, byte[] logo, Date created, String theme, Set<Users> userses, Set<Board> boards) {
        this.code = code;
        this.name = name;
        this.logo = logo;
        this.created = created;
        this.theme = theme;
        this.userses = userses;
        this.boards = boards;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 20)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "logo")
    public byte[] getLogo() {
        return this.logo;
    }

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "theme", length = 20)
    public String getTheme() {
        return this.theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "institute")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "institute")
    public Set<Board> getBoards() {
        return this.boards;
    }

    public void setBoards(Set<Board> boards) {
        this.boards = boards;
    }


}


