package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Langugae generated by hbm2java
 */
@Entity
@Table(name = "langugae"
)
@JsonIdentityInfo(
        generator = ObjectIdGenerators.StringIdGenerator.class,
        property = "langugeId")
public class Langugae implements java.io.Serializable {


    private Integer id;
    private String code;
    private String name;
    private Set<Standard> standards = new HashSet<Standard>(0);

    public Langugae() {
    }


    public Langugae(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public Langugae(String code, String name, Set<Standard> standards) {
        this.code = code;
        this.name = name;
        this.standards = standards;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 15)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "langugae")
    public Set<Standard> getStandards() {
        return this.standards;
    }

    public void setStandards(Set<Standard> standards) {
        this.standards = standards;
    }


}


