package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

/**
 * LectureSchedule generated by hbm2java
 */
@Entity
@Table(name = "lecture_schedule"
)
public class LectureSchedule implements java.io.Serializable {


    private Integer id;
    private Users users;

    @JsonBackReference(value="subject-lectureSchedule")
    private Subject subject;

    private Date from;
    private Date to;

    public LectureSchedule() {
    }

    public LectureSchedule(Users users, Subject subject, Date from) {
        this.users = users;
        this.subject = subject;
        this.from = from;
    }
    public LectureSchedule(Users users, Subject subject, Date from, Date to) {
        this.users = users;
        this.subject = subject;
        this.from = from;
        this.to = to;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taken_by")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id")
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="from", nullable=false, length=19)
    public Date getFrom() {
        return this.from;
    }

    public void setFrom(Date from) {
        this.from = from;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="to", length=19)
    public Date getTo() {
        return this.to;
    }

    public void setTo(Date to) {
        this.to = to;
    }

}


