package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LectureSchedule generated by hbm2java
 */
@Entity
@Table(name = "lecture_schedule")
public class LectureSchedule implements java.io.Serializable {


    private Integer lectureScheduleId;
    private Users users;
    private Standard standard;
    private String lectureDatetime;
    private Integer subjectId;

    public LectureSchedule() {
    }


    public LectureSchedule(Integer lectureScheduleId) {
        this.lectureScheduleId = lectureScheduleId;
    }

    public LectureSchedule(Integer lectureScheduleId, Users users, Standard standard, String lectureDatetime, Integer subjectId) {
        this.lectureScheduleId = lectureScheduleId;
        this.users = users;
        this.standard = standard;
        this.lectureDatetime = lectureDatetime;
        this.subjectId = subjectId;
    }

    @Id
    @Column(name = "lecture_schedule_id", unique = true, nullable = false)
    public Integer getLectureScheduleId() {
        return this.lectureScheduleId;
    }

    public void setLectureScheduleId(Integer lectureScheduleId) {
        this.lectureScheduleId = lectureScheduleId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taken_by")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_level_type_id")
    public Standard getStandard() {
        return this.standard;
    }

    public void setStandard(Standard standard) {
        this.standard = standard;
    }

    @Column(name = "lecture_datetime", length = 45)
    public String getLectureDatetime() {
        return this.lectureDatetime;
    }

    public void setLectureDatetime(String lectureDatetime) {
        this.lectureDatetime = lectureDatetime;
    }

    @Column(name = "subject_id")
    public Integer getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }


}


