package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LectureScheduleStatus generated by hbm2java
 */
@Entity
@Table(name="lecture_schedule_status"
)
public class LectureScheduleStatus	implements java.io.Serializable {


	 private Integer id;

	@JsonBackReference(value="lectureSchedules-status")
	private LectureSchedule lectureSchedule;

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date date;
	 private String takenBy;

	public LectureScheduleStatus() {
	}

	public LectureScheduleStatus(LectureSchedule lectureSchedule, Date date, String takenBy) {
	   this.lectureSchedule = lectureSchedule;
	   this.date = date;
	   this.takenBy = takenBy;
	}
   
	 @Id @GeneratedValue(strategy=IDENTITY)
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="schedule_id", nullable=false)
	public LectureSchedule getLectureSchedule() {
		return this.lectureSchedule;
	}
	
	public void setLectureSchedule(LectureSchedule lectureSchedule) {
		this.lectureSchedule = lectureSchedule;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="date", nullable=false, length=10)
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name="taken_by", nullable=false, length=45)
	public String getTakenBy() {
		return this.takenBy;
	}
	
	public void setTakenBy(String takenBy) {
		this.takenBy = takenBy;
	}




}


