package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParentDetails generated by hbm2java
 */
@Entity
@Table(name = "parent_details"
)
@JsonIdentityInfo(
        generator = ObjectIdGenerators.StringIdGenerator.class,
        property = "parentDetailsId")
public class ParentDetails implements java.io.Serializable {


    private Integer id;

    @JsonIgnore
    private Users users;
    private String relation;
    private String occupation;
    private Integer income;
    private String education;

    public ParentDetails() {
    }


    public ParentDetails(Users users, String relation) {
        this.users = users;
        this.relation = relation;
    }

    public ParentDetails(Users users, String relation, String occupation, Integer income, String education) {
        this.users = users;
        this.relation = relation;
        this.occupation = occupation;
        this.income = income;
        this.education = education;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "relation", nullable = false, length = 45)
    public String getRelation() {
        return this.relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    @Column(name = "occupation", length = 45)
    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    @Column(name = "income")
    public Integer getIncome() {
        return this.income;
    }

    public void setIncome(Integer income) {
        this.income = income;
    }

    @Column(name = "education", length = 30)
    public String getEducation() {
        return this.education;
    }

    public void setEducation(String education) {
        this.education = education;
    }


}


