package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionPapers generated by hbm2java
 */
@Entity
@Table(name = "question_papers")
public class QuestionPapers implements java.io.Serializable {


    private Integer id;
    private Standard standard;
    private Subject subject;
    private Board board;
    private Integer boardId;
    private byte[] content;
    private Date created;
    private String createdBy;
    private String paperName;
    private Date updated;

    public QuestionPapers() {
    }


    public QuestionPapers(Integer id, Standard standard, Subject subject, Board board, Integer boardId, byte[] content, String paperName) {
        this.id = id;
        this.standard = standard;
        this.subject = subject;
        this.board = board;
        this.boardId = boardId;
        this.content = content;
        this.paperName = paperName;
    }

    public QuestionPapers(Integer id, Standard standard, Subject subject, Board board, Integer boardId, byte[] content, Date created, String createdBy, String paperName, Date updated) {
        this.id = id;
        this.standard = standard;
        this.subject = subject;
        this.board = board;
        this.boardId = boardId;
        this.content = content;
        this.created = created;
        this.createdBy = createdBy;
        this.paperName = paperName;
        this.updated = updated;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "standard_id", nullable = false)
    public Standard getStandard() {
        return this.standard;
    }

    public void setStandard(Standard standard) {
        this.standard = standard;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", unique = true, nullable = false, insertable = false, updatable = false)
    public Board getBoard() {
        return this.board;
    }

    public void setBoard(Board board) {
        this.board = board;
    }

    @Column(name = "board_id", nullable = false)
    public Integer getBoardId() {
        return this.boardId;
    }

    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    @Column(name = "content", nullable = false)
    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created", length = 10)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "paper_name", nullable = false, length = 45)
    public String getPaperName() {
        return this.paperName;
    }

    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "updated", length = 10)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }


}


