package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name = "standard"
)
public class Standard implements java.io.Serializable {


    private Integer id;

    private Language language;

    @JsonIgnore
    private Board board;
    private String code;
    private String name;
    private Integer fees;

    @JsonBackReference(value="standard-subjects")
    private Set<Subject> subjects = new HashSet<Subject>(0);

    @JsonBackReference(value="standard-batchs")
    private Set<Batch> batchs = new HashSet<Batch>(0);

    public Standard() {
    }


    public Standard(Language language, Board board, String code, String name, Integer fees) {
        this.language = language;
        this.board = board;
        this.code = code;
        this.name = name;
        this.fees = fees;
    }

    public Standard(Language language, Board board, String code, String name, Integer fees, Set<Subject> subjects, Set<Batch> batchs) {
        this.language = language;
        this.board = board;
        this.code = code;
        this.name = name;
        this.fees = fees;
        this.subjects = subjects;
        this.batchs = batchs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_id", nullable = false)
    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "board_id", nullable = false)
    public Board getBoard() {
        return this.board;
    }

    public void setBoard(Board board) {
        this.board = board;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "fees", nullable = false)
    public Integer getFees() {
        return this.fees;
    }

    public void setFees(Integer fees) {
        this.fees = fees;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }

    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<Batch> getBatchs() {
        return this.batchs;
    }

    public void setBatchs(Set<Batch> batchs) {
        this.batchs = batchs;
    }

}


