package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name = "standard")
public class Standard implements java.io.Serializable {


    private Integer standardId;
    private Board board;
    private String name;
    private String language;
    private Integer fees;
    private Set<ClassCalendar> classCalendars = new HashSet<ClassCalendar>(0);
    private Set<QuestionPapers> questionPaperses = new HashSet<QuestionPapers>(0);
    private Set<Subject> subjects = new HashSet<Subject>(0);
    private Set<LectureSchedule> lectureSchedules = new HashSet<LectureSchedule>(0);
    private Set<ClassCalendar> classCalendars_1 = new HashSet<ClassCalendar>(0);
    private Set<StudentStandard> studentStandards = new HashSet<StudentStandard>(0);
    private Set<StudentStandard> studentStandards_1 = new HashSet<StudentStandard>(0);
    private Set<LectureSchedule> lectureSchedules_1 = new HashSet<LectureSchedule>(0);
    private Set<Subject> subjects_1 = new HashSet<Subject>(0);

    public Standard() {
    }


    public Standard(Integer standardId, Board board, String name, String language) {
        this.standardId = standardId;
        this.board = board;
        this.name = name;
        this.language = language;
    }

    public Standard(Integer standardId, Board board, String name, String language, Integer fees, Set<ClassCalendar> classCalendars, Set<QuestionPapers> questionPaperses, Set<Subject> subjects, Set<LectureSchedule> lectureSchedules, Set<ClassCalendar> classCalendars_1, Set<StudentStandard> studentStandards, Set<StudentStandard> studentStandards_1, Set<LectureSchedule> lectureSchedules_1, Set<Subject> subjects_1) {
        this.standardId = standardId;
        this.board = board;
        this.name = name;
        this.language = language;
        this.fees = fees;
        this.classCalendars = classCalendars;
        this.questionPaperses = questionPaperses;
        this.subjects = subjects;
        this.lectureSchedules = lectureSchedules;
        this.classCalendars_1 = classCalendars_1;
        this.studentStandards = studentStandards;
        this.studentStandards_1 = studentStandards_1;
        this.lectureSchedules_1 = lectureSchedules_1;
        this.subjects_1 = subjects_1;
    }

    @Id
    @Column(name = "standard_id", unique = true, nullable = false)
    public Integer getStandardId() {
        return this.standardId;
    }

    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "board_id", nullable = false)
    public Board getBoard() {
        return this.board;
    }

    public void setBoard(Board board) {
        this.board = board;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "language", nullable = false, length = 45)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "fees")
    public Integer getFees() {
        return this.fees;
    }

    public void setFees(Integer fees) {
        this.fees = fees;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<ClassCalendar> getClassCalendars() {
        return this.classCalendars;
    }

    public void setClassCalendars(Set<ClassCalendar> classCalendars) {
        this.classCalendars = classCalendars;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<QuestionPapers> getQuestionPaperses() {
        return this.questionPaperses;
    }

    public void setQuestionPaperses(Set<QuestionPapers> questionPaperses) {
        this.questionPaperses = questionPaperses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }

    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<LectureSchedule> getLectureSchedules() {
        return this.lectureSchedules;
    }

    public void setLectureSchedules(Set<LectureSchedule> lectureSchedules) {
        this.lectureSchedules = lectureSchedules;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<ClassCalendar> getClassCalendars_1() {
        return this.classCalendars_1;
    }

    public void setClassCalendars_1(Set<ClassCalendar> classCalendars_1) {
        this.classCalendars_1 = classCalendars_1;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<StudentStandard> getStudentStandards() {
        return this.studentStandards;
    }

    public void setStudentStandards(Set<StudentStandard> studentStandards) {
        this.studentStandards = studentStandards;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<StudentStandard> getStudentStandards_1() {
        return this.studentStandards_1;
    }

    public void setStudentStandards_1(Set<StudentStandard> studentStandards_1) {
        this.studentStandards_1 = studentStandards_1;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<LectureSchedule> getLectureSchedules_1() {
        return this.lectureSchedules_1;
    }

    public void setLectureSchedules_1(Set<LectureSchedule> lectureSchedules_1) {
        this.lectureSchedules_1 = lectureSchedules_1;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<Subject> getSubjects_1() {
        return this.subjects_1;
    }

    public void setSubjects_1(Set<Subject> subjects_1) {
        this.subjects_1 = subjects_1;
    }


}


