package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name = "standard"
)
public class Standard implements java.io.Serializable {


    private Integer id;

    @JsonBackReference(value="standard-board")
    private Board board;
    private String name;
    private String language;
    private Integer fees;

    @JsonManagedReference(value="questionPaper")
    private Set<QuestionPapers> questionPaperses = new HashSet<QuestionPapers>(0);

    @JsonManagedReference(value="studentStandard")
    private Set<StudentStandard> studentStandards = new HashSet<StudentStandard>(0);

    @JsonManagedReference(value="lectureSchedule")
    private Set<LectureSchedule> lectureSchedules = new HashSet<LectureSchedule>(0);

    @JsonManagedReference(value="classCalendar")
    private Set<ClassCalendar> classCalendars = new HashSet<ClassCalendar>(0);

    @JsonManagedReference(value="subject")
    private Set<Subject> subjects = new HashSet<Subject>(0);

    public Standard() {
    }


    public Standard(Board board, String name, String language) {
        this.board = board;
        this.name = name;
        this.language = language;
    }

    public Standard(Board board, String name, String language, Integer fees, Set<QuestionPapers> questionPaperses, Set<StudentStandard> studentStandards, Set<LectureSchedule> lectureSchedules, Set<ClassCalendar> classCalendars, Set<Subject> subjects) {
        this.board = board;
        this.name = name;
        this.language = language;
        this.fees = fees;
        this.questionPaperses = questionPaperses;
        this.studentStandards = studentStandards;
        this.lectureSchedules = lectureSchedules;
        this.classCalendars = classCalendars;
        this.subjects = subjects;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "board_id", nullable = false)
    public Board getBoard() {
        return this.board;
    }

    public void setBoard(Board board) {
        this.board = board;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "language", nullable = false, length = 45)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "fees")
    public Integer getFees() {
        return this.fees;
    }

    public void setFees(Integer fees) {
        this.fees = fees;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<QuestionPapers> getQuestionPaperses() {
        return this.questionPaperses;
    }

    public void setQuestionPaperses(Set<QuestionPapers> questionPaperses) {
        this.questionPaperses = questionPaperses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<StudentStandard> getStudentStandards() {
        return this.studentStandards;
    }

    public void setStudentStandards(Set<StudentStandard> studentStandards) {
        this.studentStandards = studentStandards;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<LectureSchedule> getLectureSchedules() {
        return this.lectureSchedules;
    }

    public void setLectureSchedules(Set<LectureSchedule> lectureSchedules) {
        this.lectureSchedules = lectureSchedules;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<ClassCalendar> getClassCalendars() {
        return this.classCalendars;
    }

    public void setClassCalendars(Set<ClassCalendar> classCalendars) {
        this.classCalendars = classCalendars;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "standard")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }

    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }


}


