package com.dev.ams.model;
// Generated Mar 15, 2019, 9:06:04 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentAttendance generated by hbm2java
 */
@Entity
@Table(name="student_attendance"
)
public class StudentAttendance	implements java.io.Serializable {


	 private Integer id;
	 private StudentDetails studentDetails;
	 private Date date;
	 private boolean isPresent;

	public StudentAttendance() {
	}

	public StudentAttendance(Integer id, StudentDetails studentDetails, Date date, boolean isPresent) {
	   this.id = id;
	   this.studentDetails = studentDetails;
	   this.date = date;
	   this.isPresent = isPresent;
	}
   
	 @Id 
	
	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="student_details_id", nullable=false)
	public StudentDetails getStudentDetails() {
		return this.studentDetails;
	}
	
	public void setStudentDetails(StudentDetails studentDetails) {
		this.studentDetails = studentDetails;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="date", nullable=false, length=10)
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name="is_present", nullable=false)
	public boolean isIsPresent() {
		return this.isPresent;
	}
	
	public void setIsPresent(boolean isPresent) {
		this.isPresent = isPresent;
	}




}


