package com.dev.ams.model;
// Generated Jun 5, 2019 8:13:49 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentAttendance generated by hbm2java
 */
@Entity
@Table(name = "student_attendance"
)
@JsonIdentityInfo(
        generator = ObjectIdGenerators.StringIdGenerator.class,
        property = "studentAttendanceId")
public class StudentAttendance implements java.io.Serializable {


    private Long id;
    private StudentDetails studentDetails;
    private AttendanceReason attendanceReason;
    private Date date;
    private char isPresent;

    public StudentAttendance() {
    }

    public StudentAttendance(StudentDetails studentDetails, AttendanceReason attendanceReason, Date date, char isPresent) {
        this.studentDetails = studentDetails;
        this.attendanceReason = attendanceReason;
        this.date = date;
        this.isPresent = isPresent;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_details_id", nullable = false)
    public StudentDetails getStudentDetails() {
        return this.studentDetails;
    }

    public void setStudentDetails(StudentDetails studentDetails) {
        this.studentDetails = studentDetails;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attendance_reason_id", nullable = false)
    public AttendanceReason getAttendanceReason() {
        return this.attendanceReason;
    }

    public void setAttendanceReason(AttendanceReason attendanceReason) {
        this.attendanceReason = attendanceReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", nullable = false, length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "is_present", nullable = false, length = 1)
    public char getIsPresent() {
        return this.isPresent;
    }

    public void setIsPresent(char isPresent) {
        this.isPresent = isPresent;
    }


}


