package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject"
)
public class Subject implements java.io.Serializable {


    private Integer id;

    @JsonBackReference(value="subject")
    private Standard standard;
    private String name;

    @JsonManagedReference(value="subject-chapter")
    private Set<Chapter> chapters = new HashSet<Chapter>(0);

    @JsonManagedReference(value="subject-questionPapers")
    private Set<QuestionPapers> questionPaperses = new HashSet<QuestionPapers>(0);

    @JsonManagedReference(value="subject-lectureSchedule")
    private Set<LectureSchedule> lectureSchedules = new HashSet<LectureSchedule>(0);

    public Subject() {
    }

    public Subject(Standard standard, String name, Set<Chapter> chapters, Set<QuestionPapers> questionPaperses, Set<LectureSchedule> lectureSchedules) {
        this.standard = standard;
        this.name = name;
        this.chapters = chapters;
        this.questionPaperses = questionPaperses;
        this.lectureSchedules = lectureSchedules;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "standard_id")
    public Standard getStandard() {
        return this.standard;
    }

    public void setStandard(Standard standard) {
        this.standard = standard;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<Chapter> getChapters() {
        return this.chapters;
    }

    public void setChapters(Set<Chapter> chapters) {
        this.chapters = chapters;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<QuestionPapers> getQuestionPaperses() {
        return this.questionPaperses;
    }

    public void setQuestionPaperses(Set<QuestionPapers> questionPaperses) {
        this.questionPaperses = questionPaperses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<LectureSchedule> getLectureSchedules() {
        return this.lectureSchedules;
    }

    public void setLectureSchedules(Set<LectureSchedule> lectureSchedules) {
        this.lectureSchedules = lectureSchedules;
    }


}


