package com.dev.ams.model;
// Generated Mar 2, 2019, 9:35:18 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject")
public class Subject implements java.io.Serializable {


    private Integer subjectId;
    private Standard standard;
    private String subjectName;
    private Set<Chapter> chapters = new HashSet<Chapter>(0);
    private Set<Chapter> chapters_1 = new HashSet<Chapter>(0);
    private Set<QuestionPapers> questionPaperses = new HashSet<QuestionPapers>(0);

    public Subject() {
    }


    public Subject(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public Subject(Integer subjectId, Standard standard, String subjectName, Set<Chapter> chapters, Set<Chapter> chapters_1, Set<QuestionPapers> questionPaperses) {
        this.subjectId = subjectId;
        this.standard = standard;
        this.subjectName = subjectName;
        this.chapters = chapters;
        this.chapters_1 = chapters_1;
        this.questionPaperses = questionPaperses;
    }

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name = "subject_id", unique = true, nullable = false)
    public Integer getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_id")
    public Standard getStandard() {
        return this.standard;
    }

    public void setStandard(Standard standard) {
        this.standard = standard;
    }

    @Column(name = "subject_name", length = 45)
    public String getSubjectName() {
        return this.subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<Chapter> getChapters() {
        return this.chapters;
    }

    public void setChapters(Set<Chapter> chapters) {
        this.chapters = chapters;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<Chapter> getChapters_1() {
        return this.chapters_1;
    }

    public void setChapters_1(Set<Chapter> chapters_1) {
        this.chapters_1 = chapters_1;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "subject")
    public Set<QuestionPapers> getQuestionPaperses() {
        return this.questionPaperses;
    }

    public void setQuestionPaperses(Set<QuestionPapers> questionPaperses) {
        this.questionPaperses = questionPaperses;
    }


}


