package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TakeUpDefaulterCalendar generated by hbm2java
 */
@Entity
@Table(name = "take_up_defaulter_calendar"
)
public class TakeUpDefaulterCalendar implements java.io.Serializable {


    private Integer id;
    private Users users;
    private ClassCalendar classCalendar;

    public TakeUpDefaulterCalendar() {
    }

    public TakeUpDefaulterCalendar(Users users, ClassCalendar classCalendar) {
        this.users = users;
        this.classCalendar = classCalendar;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_calendar_id", nullable = false)
    public ClassCalendar getClassCalendar() {
        return this.classCalendar;
    }

    public void setClassCalendar(ClassCalendar classCalendar) {
        this.classCalendar = classCalendar;
    }


}


