package com.dev.ams.model;
// Generated Mar 3, 2019, 8:14:57 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestResult generated by hbm2java
 */
@Entity
@Table(name = "test_result"
)
public class TestResult implements java.io.Serializable {


    private Integer id;
    private Users users;
    private ClassCalendar classCalendar;
    private Integer marksObtained;
    private Integer outOf;
    private String status;

    public TestResult() {
    }

    public TestResult(Users users, ClassCalendar classCalendar, Integer marksObtained, Integer outOf, String status) {
        this.users = users;
        this.classCalendar = classCalendar;
        this.marksObtained = marksObtained;
        this.outOf = outOf;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_calendar_id")
    public ClassCalendar getClassCalendar() {
        return this.classCalendar;
    }

    public void setClassCalendar(ClassCalendar classCalendar) {
        this.classCalendar = classCalendar;
    }

    @Column(name = "marks_obtained")
    public Integer getMarksObtained() {
        return this.marksObtained;
    }

    public void setMarksObtained(Integer marksObtained) {
        this.marksObtained = marksObtained;
    }

    @Column(name = "out_of")
    public Integer getOutOf() {
        return this.outOf;
    }

    public void setOutOf(Integer outOf) {
        this.outOf = outOf;
    }

    @Column(name = "status", length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


}


